Zagabi-LikeLion/BackEnd

.gitignore

- # #4 
- Application.yml ignore 처리
- 바로 머지하겠습니다!

✨feat: yml파일 ingore 처리(#4)

---

src/main/java/org/likelion/zagabi/Domain/Value/Entity/Value.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Controller/ValueChangeLogController.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Dto/request/CreateValueChangeLogDto.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Dto/response/ValueChangeLogResponseDto.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Entity/ChangeType.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Entity/ValueChangeLog.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Repository/ValueChangeLogRepository.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Service/ValueChangeLogQueryService.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Service/ValueChangeLogService.java

- #12 
- 가치관 변화 기록 API 생성
- 아직 완성 안된 부분이 있어서 (ex : category, user 등등) 테스트는 아직 못해봤습니다.

✨  feat : 가치관 변화 기록 API 생성 (#12)

---

src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Controller/ValueTrashCanController.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Dto/request/CreateValueTrashCanRequestDto.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Dto/response/ValueTrashCanResponseDto.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Entity/ValueTrashCan.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Repository/ValueTrashCanRepository.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Service/ValueTrashCanQueryService.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Service/ValueTrashCanService.java

- #8 
- 가치관 휴지통 API 개발 완료 했습니다
- 가치관 휴지통 전체 조회 API는 유저쪽과 인증, 인가가 구현되야 테스트할 수 있어서 아직 테스트를 해보진 못했습니다

✨  feat : 가치관 휴지통 API 개발 (#8)

---

src/main/java/org/likelion/zagabi/Domain/Category/Service/ValueCategoryService.java
src/main/java/org/likelion/zagabi/Domain/Value/Repository/ValueRepository.java

- #16 
- 카테고리 삭제 시 카테고리 안의 모든 가치관이 삭제될 수 있게 하였습니다.

♻️refactor: 카테고리와 가치관 연결

---

src/main/java/org/likelion/zagabi/Domain/Category/Entity/ValueCategory.java
src/main/java/org/likelion/zagabi/Domain/Value/Entity/Value.java
src/main/java/org/likelion/zagabi/Domain/Value/Service/ValueService.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Dto/request/CreateValueChangeLogDto.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Dto/response/ValueChangeLogResponseDto.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Entity/ValueChangeLog.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Service/ValueChangeLogService.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Entity/ValueTrashCan.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Service/ValueTrashCanQueryService.java

- #18 
- 카테고리 측면이 완성되어서 저번에 미처 못했던 부분들 연결했습니다.
-

♻ refactor : 가치관 변화 기록과 가치관 휴지통 테스트

---

src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ChangeNicknameRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ChangePwRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ForgotPwRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/UserSignUpRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Entity/User.java
src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Exception/JwtAuthenticationEntryPoint.java
src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Filter/JwtAuthenticationFilter.java
src/main/java/org/likelion/zagabi/Domain/Account/Jwt/UserDetails/CustomUserDetails.java
src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Util/JwtProvider.java
src/main/java/org/likelion/zagabi/Domain/Account/Repository/UserJpaRepository.java
src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountService.java
src/main/java/org/likelion/zagabi/Domain/Account/Service/UserService.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Entity/ValueTrashCan.java
src/main/java/org/likelion/zagabi/Global/Config/CorsConfig.java
src/main/java/org/likelion/zagabi/Global/Config/SecurityConfig.java
src/main/java/org/likelion/zagabi/Global/Config/SwaggerConfig.java

- # #20 
- 인증&인가 구현 완료
- swagger 적용
- [주의사항](http://localhost:8080/swagger-ui/index.html) 해당 url로 들어가면 swagger로 편하게 테스트 가능합니다.

[Feature] 인증&인가 최종구현 및 스웨거 적용 완료

---

src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ChangeNicknameRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/UserSignUpRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Entity/User.java
src/main/java/org/likelion/zagabi/Domain/Account/Jwt/Filter/JwtAuthenticationFilter.java
src/main/java/org/likelion/zagabi/Domain/Account/Jwt/UserDetails/CustomUserDetails.java
src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountService.java

- #25 
---
---
---
- asdf1234?로 변경👆
- asdf1234!로 변경👍
- 암호화 된 비번이 변경됨.
---
- 닉네임 변경 완료
---
---
- 삭제 완료
---
- 닉네임 변경 PutMapping -> PatchMapping으로 변경
- AccountController에 @Valid 추가
- ChangeNicknameRequestDto에 validation 추가
- UserSignUpRequestDto에서 role 삭제
- User 엔티티에서 role 삭제
- JwtAuthenticationFilter의 authenticateAccessToken 메서드 코드 수정
- CustomUserDetails의 getAuthorities 메서드에서 빈 collection을 반환하도록 수정
- AccountService의 changeNickname에서 userJpaRepository.save(user) 코드 삭제

♻️refactor: Account 부분 role 값 삭제 및 코드 리팩토링 (#25)

---

src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
src/main/java/org/likelion/zagabi/Global/Config/SecurityConfig.java

- # #26 
- 토큰 재발급 기능 구현
- 피드백 부탁드립니다!

[FEATURE] 토큰 재발급 기능 구현

---

src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java

- # #31 
- accountController에서성공 시, 메세지 출력되도록 구현 완료

[REFACTOR] accountController에서성공 시, 메세지 출력되도록 구현 완료

---

.gitignore
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/UserSignUpRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Entity/SecurityQuestion.java
src/main/java/org/likelion/zagabi/Domain/Account/Entity/User.java
src/main/java/org/likelion/zagabi/Domain/Account/Repository/SecurityQuestionRepository.java
src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountService.java

- # #33 
- 보안 질문 엔티티 추가
- 피드백 부탁드립니다

[FEATURE] 보안 질문 엔티티 추가

---

src/main/java/org/likelion/zagabi/Domain/Account/Jwt/UserDetails/CustomUserDetails.java
src/main/java/org/likelion/zagabi/Domain/Diary/Controller/DiaryController.java
src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Request/DiaryRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Request/UpdateDiaryRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Diary/Entity/Diary.java
src/main/java/org/likelion/zagabi/Domain/Diary/Repository/DiaryRepository.java
src/main/java/org/likelion/zagabi/Domain/Diary/Service/DiaryQueryService.java
src/main/java/org/likelion/zagabi/Domain/Diary/Service/DiaryService.java

- #22 
- 일기 API와 인증/인가 부분 연결하였습니다
- diary_question
- diary
---
---
---
---
---
---
- 리뷰 부탁드립니다!

♻️refactor: 일기 API와 인증/인가 부분 연결 (#22)

---

src/main/java/org/likelion/zagabi/Domain/Value/Controller/ValueController.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Controller/ValueChangeLogController.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Entity/ValueChangeLog.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Service/ValueChangeLogQueryService.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Service/ValueChangeLogService.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Controller/ValueTrashCanController.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Service/ValueTrashCanQueryService.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Service/ValueTrashCanService.java

- #24 
- 인증 인가 부분 추가해서 모든 API 요청 테스트 했습니다
- 주의사항

♻  refactor : 가치관, 가치관 기록, 가치관 휴지통 인증 인가 연결 (#24)

---

src/main/java/org/likelion/zagabi/Domain/Category/Controller/ValueCategoryController.java
src/main/java/org/likelion/zagabi/Domain/Category/Entity/ValueCategory.java
src/main/java/org/likelion/zagabi/Domain/Category/Repository/ValueCategoryRepository.java
src/main/java/org/likelion/zagabi/Domain/Category/Service/ValueCategoryQueryService.java
src/main/java/org/likelion/zagabi/Domain/Category/Service/ValueCategoryService.java

- #36 
- ValueCategory와 인증/인가 부분 연결완료하였습니다.
---
---
- DB 상황
- user_id가 1인 유저
- user_id가 2인 유저
---
---
- 리뷰 부탁드립니다!

♻️refactor: ValueCategory와 인증/인가 부분 연결 (#36)

---

.gitignore

- # #39 
- 보안질문 데이터 추가 및 파일 ignore처리

[FEATURE] 보안질문 데이터 추가 및 파일 ignore처리

---

.gitignore
src/main/java/org/likelion/zagabi/Global/Common/DataLoader.java

- # #41 
- 질문데이터(security&diary) 영구적으로 자동 추가되도록 수정
- 주의사항

[REFACTOR] 질문데이터(security&diary) 영구적으로 자동 추가되도록 수정

---

src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Response/SecurityQuestionResponseDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountQueryService.java

[FEATURE] 보안 질문 조회 API 구현

---

Dockerfile
build.gradle

cicd : Dockerfile 생성 (#49)

---

.github/workflows/cicd.yml

cicd : Create cicd.yml

---

src/main/java/org/likelion/zagabi/Domain/Value/Controller/ValueController.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Controller/ValueChangeLogController.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Controller/ValueTrashCanController.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Dto/response/ValueTrashCanResponseDto.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Entity/ValueTrashCan.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Service/ValueTrashCanService.java

- #52 
- 스웨거 설명 추가
- 가치관 휴지통 생성 할때 생성 시간이랑 카테고리 이름까지 반환하는 것으로 수정했습니다
- 주의사항

✨  feat : 스웨거 설명 추가 및 가치관 휴지통 수정 (#52)

---

src/main/java/org/likelion/zagabi/Domain/Category/Controller/ValueCategoryController.java
src/main/java/org/likelion/zagabi/Domain/Category/Dto/Request/ValueCategoryRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Category/Dto/Response/ValueCategoryResponseDto.java
src/main/java/org/likelion/zagabi/Domain/Diary/Controller/DiaryController.java
src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Request/DiaryRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Request/UpdateDiaryRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Response/DiaryQuestionResponseDto.java
src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Response/DiaryResponseDto.java

- #56 
- Diary , ValueCategory 스웨거 추가

✨feat: Diary , ValueCategory 스웨거 추가 (#56)

---

src/main/java/org/likelion/zagabi/Domain/Value/Repository/ValueRepository.java
src/main/java/org/likelion/zagabi/Domain/Value/Service/ValueService.java
src/main/java/org/likelion/zagabi/Domain/ValueTrashCan/Service/ValueTrashCanService.java

- #58 
- 카테고리가 여러 개 일때 랭킹이 겹치면 랭킹변화할때 생기는 오류 수정했습니다
- 주의사항

🐛fix : 카테고리가 여러 개 일때 랭킹이 겹치면 랭킹변화할때 생기는 오류 수정(#58)

---

src/main/java/org/likelion/zagabi/Domain/Diary/Controller/DiaryController.java
src/main/java/org/likelion/zagabi/Domain/Diary/Repository/DiaryRepository.java
src/main/java/org/likelion/zagabi/Domain/Diary/Service/DiaryQueryService.java

- #64 
-  Diary 전체 조회 API 추가하였고 테스트 완료하였습니다!

✨feat: Diary 전체 조회 API 추가 (#64)

---

src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Response/DiaryResponseDto.java

🐛fix: 일기 조회 시 Response에 ID값 추가 (#70)

---

build.gradle
src/main/java/org/likelion/zagabi/Domain/Diary/Dto/Response/DiaryResponseDto.java
src/main/java/org/likelion/zagabi/Domain/EmailAuth/Controller/EmailAuthController.java
src/main/java/org/likelion/zagabi/Domain/EmailAuth/Service/EmailAuthService.java
src/main/java/org/likelion/zagabi/Global/Config/CorsConfig.java
src/main/java/org/likelion/zagabi/Global/Config/EmailConfig.java
src/main/java/org/likelion/zagabi/Global/Config/SecurityConfig.java
src/main/java/org/likelion/zagabi/Global/Sender/DefaultEmailSender.java

✨feat: 이메일 인증 기능 구현 - 지명 (#66)

---

src/main/java/org/likelion/zagabi/Domain/Value/Entity/Value.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Entity/ValueChangeLog.java
src/main/java/org/likelion/zagabi/Domain/ValueChangeLog/Service/ValueChangeLogService.java

- #72 
- Value와 ValueChangelog 연관관계 삭제했습니다
- 주의사항

🐛 fix : 로그 생성 후 가치관 휴지통 이동 시 해당 로그 삭제되는 버그 수정 (#72)

---

src/main/java/org/likelion/zagabi/Domain/Account/Controller/AccountController.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/ForgotPwRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Request/getTokenForPwRequestDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Response/ForgotPwResponseDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Dto/Response/getTokenForPwResponseDto.java
src/main/java/org/likelion/zagabi/Domain/Account/Service/AccountService.java

[FIX] 비밀번호 분실 및 변경 로직 수정
